app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, FileField
from wtforms.validators import InputRequired, Length
#######################
### FORM MANAGEMENT ###
#######################

# form for users to sign in on home page
class loginForm(FlaskForm):
    username = StringField('Username', validators=[InputRequired(), Length(min=10, max=40)])
    password = StringField('Password', validators=[InputRequired(), Length(min=10, max=40)])
    submit = SubmitField('Submit')

class registerForm(loginForm):
    email = StringField('email', validators=[InputRequired(), Length(min=4, max=40)])
    
class fileSubmissionForm(FlaskForm):
    file = FileField('file', validators=[InputRequired()])

app/__init__.py
from flask import Flask, render_template, request, redirect, Blueprint, url_for
from dotenv import load_dotenv
import os
from werkzeug.utils import secure_filename
from flask_wtf.csrf import CSRFProtect
###################
### APPLICATION ###
###################
def create_app():
    load_dotenv()
    app = Flask(__name__)
    csrf = CSRFProtect(app)
    app.config.from_mapping(
        SECRET_KEY = os.getenv('key'),
        DATABASE = os.path.join(app.instance_path, os.getenv('db')),
        UPLOAD_FOLDER = os.path.join(app.instance_path, 'uploads')
    )
    if not os.path.exists(app.instance_path):
        os.makedirs(app.instance_path)
    from . import db
    db.init_app(app)
    
    from .authviews import authviews
    from .views import views
    app.register_blueprint(authviews, url_prefix='/auth')
    app.register_blueprint(views, url_prefix='/')
        
    return app

app/app.py
from app import create_app

app = create_app()

if __name__ == '__main__':
    app.run(debug=True)

app/views.py
from flask import Blueprint, redirect, url_for, request, render_template, flash, get_flashed_messages, current_app, jsonify
from werkzeug.utils import secure_filename
from .forms import fileSubmissionForm
from .Utils.readLang import readJson
from .Utils import randomString
from .transfer import *
import os
views = Blueprint('views', __name__)

# Add this route to redirect from the root ("/") to "/auth/login" eventually move to a standard views.py file
@views.route('/', methods=['GET'])
def root():
    return redirect(url_for('authviews.login'))

@views.route('/dashboard', methods=['GET', 'POST'])
def dashboard():
    form = fileSubmissionForm()
    fileType = ""

    if request.method == 'POST':
        # Debugging: check what's inside request.files
        if not request.files:
            flash('No files found in the request.', 'error')
            return redirect(request.url)

        # Check if the POST request has the file part
        if 'file' not in request.files:
            flash('No file part', 'error')
            return redirect(request.url)

        file = request.files['file']

        # If the user does not select a file, the browser submits an empty file without a filename.
        if file.filename == '':
            flash('No selected file', 'error')
            return redirect(request.url)

        # Secure the filename and save the file to the specified folder
        filename = secure_filename(file.filename)
        file.save(os.path.join(current_app.config['UPLOAD_FOLDER'], filename))

        # You can process the file here (e.g., reading the file or extracting its type)
        filesplit = filename.split('.')
        fileType = readJson(filename)  # If you want to process the file further
        flash('File successfully uploaded', 'success')
        # start the SSH connection for copy
        dirString = randString(16)
        paramiko_copy(file.filename, dirString)
        
        return render_template('dashboard.html', form=form, fileType=fileType, fileName=filename)
    else:
        return render_template('dashboard.html', form=form)
    

app/templates/dashboard.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
    <link rel="stylesheet" href="{{url_for('static', filename='dist/output.css')}}">
    <script defer src="{{ url_for('static', filename='js/dashboard.js') }}"></script>
</head>
<body class="bg-gray1 overflow-y-hidden">

    <!-- Container for responsive layout -->
    <div class="flex flex-col md:flex-row h-screen">
        <!-- Sidebar -->
        <div class="w-full md:w-64 bg-gray2 text-white h-auto md:h-full">
            <div class="p-8 text-4xl text-center font-black text-green1">
                CodeGuard
            </div>
            <div class="mt-4">
                <h4 class="text-gray-400 p-2 text-sm">Previous Submissions...</h4>
            </div>
            <nav>
                <a href="#" class="block py-2.5 px-4 text-gray-200 hover:bg-gray-700 hover:text-white transition duration-200">Placeholder for previous submissions</a>
                <a href="#" class="block py-2.5 px-4 text-gray-200 hover:bg-gray-700 hover:text-white transition duration-200">Placeholder for previous submissions</a>
                <a href="#" class="block py-2.5 px-4 text-gray-200 hover:bg-gray-700 hover:text-white transition duration-200">Placeholder for previous submissions</a>
                <a href="#" class="block py-2.5 px-4 text-gray-200 hover:bg-gray-700 hover:text-white transition duration-200">Placeholder for previous submissions</a>
            </nav>
        </div>
    
        <!-- Main content -->
        <div class="w-full bg-gray3 flex-1 m-4 rounded-3xl shadow-2xl ">
        <!-- Top settings bar -->
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    <div class="flash mb-4 flex top-8 right-10 z-50 w-1/2 fixed text-nowrap text-center justify-center"> <!-- Center the inner div -->
                        <div class="bg-red1 border-solid rounded-lg z-10 w-1/4">
                            <ul>
                                {% for category, message in messages %}
                                    <li class="list-none {% if category == 'error' %} bg-red-100 border border-red-400 text-red-700 {% elif category == 'success' %} bg-green-100 border border-green-400 text-green-700 {% endif %} px-4 py-3 rounded relative" role="alert">
                                        <span class="block sm:inline">{{ message }}</span>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                {% endif %}
            {% endwith %}
             <div class="flex items-center justify-between p-4 border-solid border-b-2 border-gray-300">
                <h1 class="text-3xl font-bold text-gray-300">Code Analysis</h1>
                <div class="flex items-center relative">
                    <form method=post enctype=multipart/form-data action="{{ url_for('views.dashboard') }}">
                        {{ form.csrf_token }}
                        {{ form.hidden_tag() }}
                        <!-- Hidden actual file input -->
                        <input id="fileinput" type="file" name="file" class="hidden">
                        <!-- Custom button and label -->
                        <label for="fileinput" id="filelabel" class="mr-8 bg-green1 hover:bg-green2 rounded-full p-2 text-white border-solid border-1 border-black cursor-pointer">
                            Upload File
                        </label>
                        <button type="submit" class="mr-8 bg-green1 hover:bg-green2 rounded-full p-2 text-white border-solid border-1 border-black cursor-pointer">
                            Analyze
                        </button>
                    </form>
                    <button class="flex items-center justify-center rounded-full border-solid border-2 border-black Shadow-2xl">
                        <img id="usersettings" class="object-contain w-10 h-10 bg-gray-300 rounded-full " src="{{ url_for('static', filename='images/person-svgrepo-com.svg') }}">
                    </button>
                    <div id="usermenu" class="hidden absolute left-0 bg-stone-700 border border-stone-900 rounded z-10 top-full shadow-2xl">
                        <button class="block w-full p-2 rounded-md text-green1 hover:text-green2">Settings</button>
                        <button class="p-2 rounded-md text-green1 hover:text-green2">Logout</button>
                    </div>
                </div>
            </div>
            <!-- Code previewer and results section -->
             <div class="flex items-center justify-between p-4 border-solid border-b-2 border-gray-300 w-full h-full">
                <div class="w-2/3 h-full"> <!--Code preview-->
                    <div class="w-full flex justify-between"> 
                        {% if fileName %}
                            <h2 class="inline-block text-green1 text-lg">filename: <span class="text-white">{{ fileName }}</span></h2>
                            <h2 class="inline-block text-green1 text-lg">Detected Language: <span class="text-white">{{ fileType }}</span></h2>
                        {% endif %}
                    </div>
                </div>
                <div class="w-1/3 h-full"> <!--Results-->test
                </div>
            </div>
        </div>
    </div>
</body>
</html>

app/templates/login.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="{{url_for('static', filename='dist/output.css')}}">
</head>
<body class="bg-gray1 h-screen flex items-center justify-center">
    <!-- Left Section -->
    <div class="w-1/3 flex flex-col items-center pb-10 mx-auto pl-40"> <!-- Centered content with mx-auto and flex alignment -->
        <h2 class="text-6xl text-green1 pb-10 text-left font-extrabold">
            <span class="block p-4">Secure.</span>  <!-- Reduced padding to make text fit more snugly -->
            <span class="block p-4">Optimize.</span>
            <span class="block p-4">Enhance.</span>
            <span class="block p-4">CodeGuard.</span>
        </h2>        
        <img class="w-48 h-48 object-contain mb-4" src="{{ url_for('static', filename='images/C.png') }}" alt="Codeguard Image"> <!-- Adjusted image size -->
    </div>
    
    
    <!-- Right Section (Login Form) -->
    <div class="w-2/3 flex flex-col items-center justify-center h-full p-10">
        <div class="bg-gray2 w-full max-w-md p-8 rounded-2xl shadow-lg">
            <h1 class="text-4xl font-bold text-green1 text-center mb-2">CodeGuard</h1>
            <h2 class="text-lg font-bold text-white text-center mb-4">Login</h2>

            <!-- Flash Messages -->
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    <div class="mb-4 border-solid rounded-lg flash {% if category == 'error' %} bg-red1 {% elif category == 'success' %} bg-green2 {% endif %}">
                        {% for category, message in messages %}
                            <div class="text-white bg-{{ category }}-500 p-2 rounded mb-2">
                                {{ message }}
                            </div>
                        {% endfor %}
                    </div>
                {% endif %}
            {% endwith %}

            <!-- Login Form -->
            <form method="POST" action="{{ url_for('authviews.login') }}">
                {{ form.csrf_token }}
                {{ form.hidden_tag() }}
                
                <div class="mb-4">
                    <label for="username" class="block text-white mb-1">{{ form.username.label }}</label>
                    {{ form.username(class="w-full bg-gray3 h-10 px-3 rounded-lg shadow-lg") }}
                </div>

                <div class="mb-4">
                    <label for="password" class="block text-white mb-1">{{ form.password.label }}</label>
                    {{ form.password(class="w-full bg-gray3 h-10 px-3 rounded-lg shadow-lg", type="password") }}
                </div>

                <div class="flex justify-between items-center mb-6">
                    <button class="bg-green1 text-white py-2 px-6 rounded-lg shadow-lg transition duration-300 hover:bg-green2">Login</button>
                    <p class="text-white">Don't have an account? <a href="{{ url_for('authviews.register') }}" class="underline text-green1 hover:text-green2">Register</a></p>
                </div>
            </form>
        </div>
    </div>
</body>
</html>

app/templates/register.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Code Analysis</title>
    <link rel="stylesheet" href="{{url_for('static', filename='dist/output.css')}}">
</head>
<body class="bg-gray1 h-screen flex items-center justify-center">
    <!-- Left Section -->
    <div class="w-1/3 flex flex-col items-center pb-10 mx-auto pl-40"> <!-- Centered content with mx-auto and flex alignment -->
        <h2 class="text-6xl text-green1 pb-10 text-left font-extrabold">
            <span class="block p-4">Secure.</span>  <!-- Reduced padding to make text fit more snugly -->
            <span class="block p-4">Optimize.</span>
            <span class="block p-4">Enhance.</span>
            <span class="block p-4">CodeGuard.</span>
        </h2>        
        <img class="w-48 h-48 object-contain mb-4" src="{{ url_for('static', filename='images/C.png') }}" alt="Codeguard Image"> <!-- Adjusted image size -->
    </div>
    <!-- Right Section (Login Form) -->
    <div class="w-2/3 flex flex-col items-center justify-center h-full p-10">
        <div class="bg-gray2 w-full max-w-md p-8 rounded-2xl shadow-lg">
            <h1 class="text-4xl font-bold text-green1 text-center mb-2">CodeGuard</h1>
            <h2 class="text-lg font-bold text-white text-center mb-4">Register</h2>
            <!-- Logic for error or success flashing -->
            <!-- Flash Messages -->
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    <div class="flash mb-4 border-solid rounded-lg{% if category == 'error' %} bg-red1 {% elif category == 'success' %} bg-green2 {% endif %}">
                        {% for category, message in messages %}
                            <div class="text-white bg-{{ category }}-500 p-2 rounded mb-2">
                                {{ message }}
                            </div>
                        {% endfor %}
                    </div>
                {% endif %}
            {% endwith %}                                 
            <!-- End logic for error or success flashing-->         
            <form method="POST" action="{{ url_for('authviews.register') }}">
                <div class="mb-4">
                    {{ form.csrf_token }}
                    {{ form.hidden_tag() }}
                    <div class="mb-4">
                        <label for="username" class="block text-white mb-1">{{ form.username.label }}</label>
                        {{ form.username(class="w-full bg-gray3 h-10 px-3 rounded-lg shadow-lg") }}
                    </div>
    
                    <div class="mb-4">
                        <label for="password" class="block text-white mb-1">{{ form.password.label }}</label>
                        {{ form.password(class="w-full bg-gray3 h-10 px-3 rounded-lg shadow-lg", type="password") }}
                    </div>

                    <div class="mb-4">
                        <label for="email" class="block text-white mb-1">{{ form.email.label }}</label>
                        {{ form.email(class="w-full bg-gray3 h-10 px-3 rounded-lg shadow-lg", type="email") }}
                    </div>

                    <div class="flex justify-between items-center mb-6">
                        <button class="bg-green1 text-white py-2 px-6 rounded-lg shadow-lg transition duration-300 hover:bg-green2">Login</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</body>
</html>